version: "3"
services:
  nodejs_app:
    container_name: nodejs_app
    build: ./nodejs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=pessoas
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pessoas

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - nodejs_app
